//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTemplate1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FiscalisationServiceSoap")]
    public interface FiscalisationServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterTCR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProjectTemplate1.ServiceReference1.ResultLog RegisterTCR(string IDAgjenti, string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterTCR", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterTCRAsync(string IDAgjenti, string businessUnitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTCRByIDAgjenti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTCRByIDAgjenti(string IDAgjenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTCRByIDAgjenti", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTCRByIDAgjentiAsync(string IDAgjenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfigurationByIDAgjenti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProjectTemplate1.ServiceReference1.ResultConfiguration GetConfigurationByIDAgjenti(string IDAgjenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfigurationByIDAgjenti", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultConfiguration> GetConfigurationByIDAgjentiAsync(string IDAgjenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNumriFiskByIDAgjenti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateNumriFiskByIDAgjenti(string IDAgjenti, string TCRCode, int IDN, int LevizjeIDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNumriFiskByIDAgjenti", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateNumriFiskByIDAgjentiAsync(string IDAgjenti, string TCRCode, int IDN, int LevizjeIDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckCorrectiveInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckCorrectiveInvoice(string invId, string DeviceID, string TCRCode, string OperatorCode, string BusinessUnitCode, string NIPT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckCorrectiveInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CheckCorrectiveInvoiceAsync(string invId, string DeviceID, string TCRCode, string OperatorCode, string BusinessUnitCode, string NIPT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTCRRequestByMobleIdRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTCRRequestByMobleIdRef(string MobleIdRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTCRRequestByMobleIdRef", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTCRRequestByMobleIdRefAsync(string MobleIdRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterCashDeposit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProjectTemplate1.ServiceReference1.ResultLog RegisterCashDeposit(ProjectTemplate1.ServiceReference1.RegisterCashDepositInputRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterCashDeposit", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterCashDepositAsync(ProjectTemplate1.ServiceReference1.RegisterCashDepositInputRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProjectTemplate1.ServiceReference1.ResultLog RegisterInvoice(ProjectTemplate1.ServiceReference1.RegisterInvoiceInputRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterInvoiceAsync(ProjectTemplate1.ServiceReference1.RegisterInvoiceInputRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterWTN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProjectTemplate1.ServiceReference1.ResultLog RegisterWTN(ProjectTemplate1.ServiceReference1.RegisterWTNInputRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterWTN", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterWTNAsync(ProjectTemplate1.ServiceReference1.RegisterWTNInputRequest req);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime createdField;
        
        private string requestField;
        
        private string responseField;
        
        private string responseObjectField;
        
        private Status statusField;
        
        private RequestType requestTypeField;
        
        private string stacktraceField;
        
        private string messageField;
        
        private string mobileIdRefField;
        
        private string operatorCodeField;
        
        private string qRCodeLinkField;
        
        private string tCRBusinessCodeField;
        
        private string nSLFField;
        
        private string nIVFField;
        
        private string responseUUIDField;
        
        private string eICField;
        
        private string responseUUIDSHField;
        
        private string nIVFSHField;
        
        private string nSLFSHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("Request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ResponseObject {
            get {
                return this.responseObjectField;
            }
            set {
                this.responseObjectField = value;
                this.RaisePropertyChanged("ResponseObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public RequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Stacktrace {
            get {
                return this.stacktraceField;
            }
            set {
                this.stacktraceField = value;
                this.RaisePropertyChanged("Stacktrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MobileIdRef {
            get {
                return this.mobileIdRefField;
            }
            set {
                this.mobileIdRefField = value;
                this.RaisePropertyChanged("MobileIdRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string QRCodeLink {
            get {
                return this.qRCodeLinkField;
            }
            set {
                this.qRCodeLinkField = value;
                this.RaisePropertyChanged("QRCodeLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TCRBusinessCode {
            get {
                return this.tCRBusinessCodeField;
            }
            set {
                this.tCRBusinessCodeField = value;
                this.RaisePropertyChanged("TCRBusinessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NSLF {
            get {
                return this.nSLFField;
            }
            set {
                this.nSLFField = value;
                this.RaisePropertyChanged("NSLF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NIVF {
            get {
                return this.nIVFField;
            }
            set {
                this.nIVFField = value;
                this.RaisePropertyChanged("NIVF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ResponseUUID {
            get {
                return this.responseUUIDField;
            }
            set {
                this.responseUUIDField = value;
                this.RaisePropertyChanged("ResponseUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string EIC {
            get {
                return this.eICField;
            }
            set {
                this.eICField = value;
                this.RaisePropertyChanged("EIC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ResponseUUIDSH {
            get {
                return this.responseUUIDSHField;
            }
            set {
                this.responseUUIDSHField = value;
                this.RaisePropertyChanged("ResponseUUIDSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NIVFSH {
            get {
                return this.nIVFSHField;
            }
            set {
                this.nIVFSHField = value;
                this.RaisePropertyChanged("NIVFSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NSLFSH {
            get {
                return this.nSLFSHField;
            }
            set {
                this.nSLFSHField = value;
                this.RaisePropertyChanged("NSLFSH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Status {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        FaultCode,
        
        /// <remarks/>
        CertificateNotValid,
        
        /// <remarks/>
        InternalError,
        
        /// <remarks/>
        TCRAlreadyRegistered,
        
        /// <remarks/>
        InProcess,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum RequestType {
        
        /// <remarks/>
        Fault,
        
        /// <remarks/>
        Undefiend,
        
        /// <remarks/>
        RegisterTCR,
        
        /// <remarks/>
        RegisterCashDeposit,
        
        /// <remarks/>
        RegisterInvoice,
        
        /// <remarks/>
        RegisterWTN,
        
        /// <remarks/>
        RegisterEinvoice,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class WTNItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nField;
        
        private string cField;
        
        private string uField;
        
        private double qField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("N");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
                this.RaisePropertyChanged("C");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
                this.RaisePropertyChanged("U");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
                this.RaisePropertyChanged("Q");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterWTNInputRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private string businessUnitCodeField;
        
        private string deviceIDField;
        
        private string invOrdNumField;
        
        private string invNumField;
        
        private System.DateTime sendDatetimeField;
        
        private decimal valueOfGoodsField;
        
        private bool startPointSTypeSpecified1Field;
        
        private WTNStartPointSType startPointSTypeField;
        
        private bool startPointSTypeFieldSpecified;
        
        private bool destinPointSTypeSpecified1Field;
        
        private WTNDestinPointSType destinPointSTypeField;
        
        private bool destinPointSTypeFieldSpecified;
        
        private WTNItemType[] transferItemsField;
        
        private string mobileRefIdField;
        
        private int subseqDelivTypeSTypeField;
        
        private string fromDeviceIdField;
        
        private string toDeviceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
                this.RaisePropertyChanged("TCRCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BusinessUnitCode {
            get {
                return this.businessUnitCodeField;
            }
            set {
                this.businessUnitCodeField = value;
                this.RaisePropertyChanged("BusinessUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("DeviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string InvOrdNum {
            get {
                return this.invOrdNumField;
            }
            set {
                this.invOrdNumField = value;
                this.RaisePropertyChanged("InvOrdNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string InvNum {
            get {
                return this.invNumField;
            }
            set {
                this.invNumField = value;
                this.RaisePropertyChanged("InvNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime SendDatetime {
            get {
                return this.sendDatetimeField;
            }
            set {
                this.sendDatetimeField = value;
                this.RaisePropertyChanged("SendDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal ValueOfGoods {
            get {
                return this.valueOfGoodsField;
            }
            set {
                this.valueOfGoodsField = value;
                this.RaisePropertyChanged("ValueOfGoods");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartPointSTypeSpecified", Order=8)]
        public bool StartPointSTypeSpecified1 {
            get {
                return this.startPointSTypeSpecified1Field;
            }
            set {
                this.startPointSTypeSpecified1Field = value;
                this.RaisePropertyChanged("StartPointSTypeSpecified1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public WTNStartPointSType StartPointSType {
            get {
                return this.startPointSTypeField;
            }
            set {
                this.startPointSTypeField = value;
                this.RaisePropertyChanged("StartPointSType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartPointSTypeSpecified {
            get {
                return this.startPointSTypeFieldSpecified;
            }
            set {
                this.startPointSTypeFieldSpecified = value;
                this.RaisePropertyChanged("StartPointSTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinPointSTypeSpecified", Order=10)]
        public bool DestinPointSTypeSpecified1 {
            get {
                return this.destinPointSTypeSpecified1Field;
            }
            set {
                this.destinPointSTypeSpecified1Field = value;
                this.RaisePropertyChanged("DestinPointSTypeSpecified1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public WTNDestinPointSType DestinPointSType {
            get {
                return this.destinPointSTypeField;
            }
            set {
                this.destinPointSTypeField = value;
                this.RaisePropertyChanged("DestinPointSType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DestinPointSTypeSpecified {
            get {
                return this.destinPointSTypeFieldSpecified;
            }
            set {
                this.destinPointSTypeFieldSpecified = value;
                this.RaisePropertyChanged("DestinPointSTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public WTNItemType[] TransferItems {
            get {
                return this.transferItemsField;
            }
            set {
                this.transferItemsField = value;
                this.RaisePropertyChanged("TransferItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string MobileRefId {
            get {
                return this.mobileRefIdField;
            }
            set {
                this.mobileRefIdField = value;
                this.RaisePropertyChanged("MobileRefId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int SubseqDelivTypeSType {
            get {
                return this.subseqDelivTypeSTypeField;
            }
            set {
                this.subseqDelivTypeSTypeField = value;
                this.RaisePropertyChanged("SubseqDelivTypeSType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FromDeviceId {
            get {
                return this.fromDeviceIdField;
            }
            set {
                this.fromDeviceIdField = value;
                this.RaisePropertyChanged("FromDeviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ToDeviceId {
            get {
                return this.toDeviceIdField;
            }
            set {
                this.toDeviceIdField = value;
                this.RaisePropertyChanged("ToDeviceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum WTNStartPointSType {
        
        /// <remarks/>
        WAREHOUSE,
        
        /// <remarks/>
        EXHIBITION,
        
        /// <remarks/>
        STORE,
        
        /// <remarks/>
        SALE,
        
        /// <remarks/>
        ANOTHER,
        
        /// <remarks/>
        CUSTOMS,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum WTNDestinPointSType {
        
        /// <remarks/>
        WAREHOUSE,
        
        /// <remarks/>
        EXHIBITION,
        
        /// <remarks/>
        STORE,
        
        /// <remarks/>
        SALE,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class VoucherType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
                this.RaisePropertyChanged("Num");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class VoucherSoldDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dField;
        
        private decimal nField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
                this.RaisePropertyChanged("D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("N");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class VouchersSoldType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VoucherSoldDataType vdField;
        
        private VoucherType[] vnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VoucherSoldDataType VD {
            get {
                return this.vdField;
            }
            set {
                this.vdField = value;
                this.RaisePropertyChanged("VD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("V", IsNullable=false)]
        public VoucherType[] VN {
            get {
                return this.vnField;
            }
            set {
                this.vnField = value;
                this.RaisePropertyChanged("VN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class InvoiceItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VouchersSoldType vsField;
        
        private string nField;
        
        private string cField;
        
        private string uField;
        
        private double qField;
        
        private decimal uPBField;
        
        private decimal uPAField;
        
        private decimal rField;
        
        private bool rFieldSpecified;
        
        private bool rrField;
        
        private bool rrFieldSpecified;
        
        private decimal pbField;
        
        private decimal vrField;
        
        private bool vrFieldSpecified;
        
        private decimal vaField;
        
        private bool vaFieldSpecified;
        
        private bool inField;
        
        private bool inFieldSpecified;
        
        private decimal paField;
        
        private ExemptFromVATSType exField;
        
        private bool exFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VouchersSoldType VS {
            get {
                return this.vsField;
            }
            set {
                this.vsField = value;
                this.RaisePropertyChanged("VS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("N");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
                this.RaisePropertyChanged("C");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
                this.RaisePropertyChanged("U");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
                this.RaisePropertyChanged("Q");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal UPB {
            get {
                return this.uPBField;
            }
            set {
                this.uPBField = value;
                this.RaisePropertyChanged("UPB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal UPA {
            get {
                return this.uPAField;
            }
            set {
                this.uPAField = value;
                this.RaisePropertyChanged("UPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
                this.RaisePropertyChanged("R");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSpecified {
            get {
                return this.rFieldSpecified;
            }
            set {
                this.rFieldSpecified = value;
                this.RaisePropertyChanged("RSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool RR {
            get {
                return this.rrField;
            }
            set {
                this.rrField = value;
                this.RaisePropertyChanged("RR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RRSpecified {
            get {
                return this.rrFieldSpecified;
            }
            set {
                this.rrFieldSpecified = value;
                this.RaisePropertyChanged("RRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PB {
            get {
                return this.pbField;
            }
            set {
                this.pbField = value;
                this.RaisePropertyChanged("PB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal VR {
            get {
                return this.vrField;
            }
            set {
                this.vrField = value;
                this.RaisePropertyChanged("VR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VRSpecified {
            get {
                return this.vrFieldSpecified;
            }
            set {
                this.vrFieldSpecified = value;
                this.RaisePropertyChanged("VRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal VA {
            get {
                return this.vaField;
            }
            set {
                this.vaField = value;
                this.RaisePropertyChanged("VA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VASpecified {
            get {
                return this.vaFieldSpecified;
            }
            set {
                this.vaFieldSpecified = value;
                this.RaisePropertyChanged("VASpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IN {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
                this.RaisePropertyChanged("IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INSpecified {
            get {
                return this.inFieldSpecified;
            }
            set {
                this.inFieldSpecified = value;
                this.RaisePropertyChanged("INSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PA {
            get {
                return this.paField;
            }
            set {
                this.paField = value;
                this.RaisePropertyChanged("PA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ExemptFromVATSType EX {
            get {
                return this.exField;
            }
            set {
                this.exField = value;
                this.RaisePropertyChanged("EX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EXSpecified {
            get {
                return this.exFieldSpecified;
            }
            set {
                this.exFieldSpecified = value;
                this.RaisePropertyChanged("EXSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum ExemptFromVATSType {
        
        /// <remarks/>
        TYPE_1,
        
        /// <remarks/>
        TYPE_2,
        
        /// <remarks/>
        TAX_FREE,
        
        /// <remarks/>
        MARGIN_SCHEME,
        
        /// <remarks/>
        EXPORT_OF_GOODS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class BuyerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IDTypeSType iDTypeField;
        
        private bool iDTypeFieldSpecified;
        
        private string iDNumField;
        
        private string nameField;
        
        private string addressField;
        
        private string townField;
        
        private CountryCodeSType countryField;
        
        private bool countryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public IDTypeSType IDType {
            get {
                return this.iDTypeField;
            }
            set {
                this.iDTypeField = value;
                this.RaisePropertyChanged("IDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDTypeSpecified {
            get {
                return this.iDTypeFieldSpecified;
            }
            set {
                this.iDTypeFieldSpecified = value;
                this.RaisePropertyChanged("IDTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IDNum {
            get {
                return this.iDNumField;
            }
            set {
                this.iDNumField = value;
                this.RaisePropertyChanged("IDNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
                this.RaisePropertyChanged("Town");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CountryCodeSType Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountrySpecified {
            get {
                return this.countryFieldSpecified;
            }
            set {
                this.countryFieldSpecified = value;
                this.RaisePropertyChanged("CountrySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum IDTypeSType {
        
        /// <remarks/>
        NUIS,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        PASS,
        
        /// <remarks/>
        VAT,
        
        /// <remarks/>
        TAX,
        
        /// <remarks/>
        SOC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum CountryCodeSType {
        
        /// <remarks/>
        ABW,
        
        /// <remarks/>
        AFG,
        
        /// <remarks/>
        AGO,
        
        /// <remarks/>
        AIA,
        
        /// <remarks/>
        ALA,
        
        /// <remarks/>
        ALB,
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        ARE,
        
        /// <remarks/>
        ARG,
        
        /// <remarks/>
        ARM,
        
        /// <remarks/>
        ASM,
        
        /// <remarks/>
        ATA,
        
        /// <remarks/>
        ATF,
        
        /// <remarks/>
        ATG,
        
        /// <remarks/>
        AUS,
        
        /// <remarks/>
        AUT,
        
        /// <remarks/>
        AZE,
        
        /// <remarks/>
        BDI,
        
        /// <remarks/>
        BEL,
        
        /// <remarks/>
        BEN,
        
        /// <remarks/>
        BES,
        
        /// <remarks/>
        BFA,
        
        /// <remarks/>
        BGD,
        
        /// <remarks/>
        BGR,
        
        /// <remarks/>
        BHR,
        
        /// <remarks/>
        BHS,
        
        /// <remarks/>
        BIH,
        
        /// <remarks/>
        BLM,
        
        /// <remarks/>
        BLR,
        
        /// <remarks/>
        BLZ,
        
        /// <remarks/>
        BMU,
        
        /// <remarks/>
        BOL,
        
        /// <remarks/>
        BRA,
        
        /// <remarks/>
        BRB,
        
        /// <remarks/>
        BRN,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BVT,
        
        /// <remarks/>
        BWA,
        
        /// <remarks/>
        CAF,
        
        /// <remarks/>
        CAN,
        
        /// <remarks/>
        CCK,
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        CHL,
        
        /// <remarks/>
        CHN,
        
        /// <remarks/>
        CIV,
        
        /// <remarks/>
        CMR,
        
        /// <remarks/>
        COD,
        
        /// <remarks/>
        COG,
        
        /// <remarks/>
        COK,
        
        /// <remarks/>
        COL,
        
        /// <remarks/>
        COM,
        
        /// <remarks/>
        CPV,
        
        /// <remarks/>
        CRI,
        
        /// <remarks/>
        CUB,
        
        /// <remarks/>
        CUW,
        
        /// <remarks/>
        CXR,
        
        /// <remarks/>
        CYM,
        
        /// <remarks/>
        CYP,
        
        /// <remarks/>
        CZE,
        
        /// <remarks/>
        DEU,
        
        /// <remarks/>
        DJI,
        
        /// <remarks/>
        DMA,
        
        /// <remarks/>
        DNK,
        
        /// <remarks/>
        DOM,
        
        /// <remarks/>
        DZA,
        
        /// <remarks/>
        ECU,
        
        /// <remarks/>
        EGY,
        
        /// <remarks/>
        ERI,
        
        /// <remarks/>
        ESH,
        
        /// <remarks/>
        ESP,
        
        /// <remarks/>
        EST,
        
        /// <remarks/>
        ETH,
        
        /// <remarks/>
        FIN,
        
        /// <remarks/>
        FJI,
        
        /// <remarks/>
        FLK,
        
        /// <remarks/>
        FRA,
        
        /// <remarks/>
        FRO,
        
        /// <remarks/>
        FSM,
        
        /// <remarks/>
        GAB,
        
        /// <remarks/>
        GBR,
        
        /// <remarks/>
        GEO,
        
        /// <remarks/>
        GGY,
        
        /// <remarks/>
        GHA,
        
        /// <remarks/>
        GIB,
        
        /// <remarks/>
        GIN,
        
        /// <remarks/>
        GLP,
        
        /// <remarks/>
        GMB,
        
        /// <remarks/>
        GNB,
        
        /// <remarks/>
        GNQ,
        
        /// <remarks/>
        GRC,
        
        /// <remarks/>
        GRD,
        
        /// <remarks/>
        GRL,
        
        /// <remarks/>
        GTM,
        
        /// <remarks/>
        GUF,
        
        /// <remarks/>
        GUM,
        
        /// <remarks/>
        GUY,
        
        /// <remarks/>
        HKG,
        
        /// <remarks/>
        HMD,
        
        /// <remarks/>
        HND,
        
        /// <remarks/>
        HRV,
        
        /// <remarks/>
        HTI,
        
        /// <remarks/>
        HUN,
        
        /// <remarks/>
        IDN,
        
        /// <remarks/>
        IMN,
        
        /// <remarks/>
        IND,
        
        /// <remarks/>
        IOT,
        
        /// <remarks/>
        IRL,
        
        /// <remarks/>
        IRN,
        
        /// <remarks/>
        IRQ,
        
        /// <remarks/>
        ISL,
        
        /// <remarks/>
        ISR,
        
        /// <remarks/>
        ITA,
        
        /// <remarks/>
        JAM,
        
        /// <remarks/>
        JEY,
        
        /// <remarks/>
        JOR,
        
        /// <remarks/>
        JPN,
        
        /// <remarks/>
        KAZ,
        
        /// <remarks/>
        KEN,
        
        /// <remarks/>
        KGZ,
        
        /// <remarks/>
        KHM,
        
        /// <remarks/>
        KIR,
        
        /// <remarks/>
        KNA,
        
        /// <remarks/>
        KOR,
        
        /// <remarks/>
        KWT,
        
        /// <remarks/>
        LAO,
        
        /// <remarks/>
        LBN,
        
        /// <remarks/>
        LBR,
        
        /// <remarks/>
        LBY,
        
        /// <remarks/>
        LCA,
        
        /// <remarks/>
        LIE,
        
        /// <remarks/>
        LKA,
        
        /// <remarks/>
        LSO,
        
        /// <remarks/>
        LTU,
        
        /// <remarks/>
        LUX,
        
        /// <remarks/>
        LVA,
        
        /// <remarks/>
        MAC,
        
        /// <remarks/>
        MAF,
        
        /// <remarks/>
        MAR,
        
        /// <remarks/>
        MCO,
        
        /// <remarks/>
        MDA,
        
        /// <remarks/>
        MDG,
        
        /// <remarks/>
        MDV,
        
        /// <remarks/>
        MEX,
        
        /// <remarks/>
        MHL,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MLI,
        
        /// <remarks/>
        MLT,
        
        /// <remarks/>
        MMR,
        
        /// <remarks/>
        MNE,
        
        /// <remarks/>
        MNG,
        
        /// <remarks/>
        MNP,
        
        /// <remarks/>
        MOZ,
        
        /// <remarks/>
        MRT,
        
        /// <remarks/>
        MSR,
        
        /// <remarks/>
        MTQ,
        
        /// <remarks/>
        MUS,
        
        /// <remarks/>
        MWI,
        
        /// <remarks/>
        MYS,
        
        /// <remarks/>
        MYT,
        
        /// <remarks/>
        NAM,
        
        /// <remarks/>
        NCL,
        
        /// <remarks/>
        NER,
        
        /// <remarks/>
        NFK,
        
        /// <remarks/>
        NGA,
        
        /// <remarks/>
        NIC,
        
        /// <remarks/>
        NIU,
        
        /// <remarks/>
        NLD,
        
        /// <remarks/>
        NOR,
        
        /// <remarks/>
        NPL,
        
        /// <remarks/>
        NRU,
        
        /// <remarks/>
        NZL,
        
        /// <remarks/>
        OMN,
        
        /// <remarks/>
        PAK,
        
        /// <remarks/>
        PAN,
        
        /// <remarks/>
        PCN,
        
        /// <remarks/>
        PER,
        
        /// <remarks/>
        PHL,
        
        /// <remarks/>
        PLW,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        POL,
        
        /// <remarks/>
        PRI,
        
        /// <remarks/>
        PRK,
        
        /// <remarks/>
        PRT,
        
        /// <remarks/>
        PRY,
        
        /// <remarks/>
        PSE,
        
        /// <remarks/>
        PYF,
        
        /// <remarks/>
        QAT,
        
        /// <remarks/>
        REU,
        
        /// <remarks/>
        ROU,
        
        /// <remarks/>
        RUS,
        
        /// <remarks/>
        RWA,
        
        /// <remarks/>
        SAU,
        
        /// <remarks/>
        SDN,
        
        /// <remarks/>
        SEN,
        
        /// <remarks/>
        SGP,
        
        /// <remarks/>
        SGS,
        
        /// <remarks/>
        SHN,
        
        /// <remarks/>
        SJM,
        
        /// <remarks/>
        SLB,
        
        /// <remarks/>
        SLE,
        
        /// <remarks/>
        SLV,
        
        /// <remarks/>
        SMR,
        
        /// <remarks/>
        SOM,
        
        /// <remarks/>
        SPM,
        
        /// <remarks/>
        SRB,
        
        /// <remarks/>
        SSD,
        
        /// <remarks/>
        STP,
        
        /// <remarks/>
        SUR,
        
        /// <remarks/>
        SVK,
        
        /// <remarks/>
        SVN,
        
        /// <remarks/>
        SWE,
        
        /// <remarks/>
        SWZ,
        
        /// <remarks/>
        SXM,
        
        /// <remarks/>
        SYC,
        
        /// <remarks/>
        SYR,
        
        /// <remarks/>
        TCA,
        
        /// <remarks/>
        TCD,
        
        /// <remarks/>
        TGO,
        
        /// <remarks/>
        THA,
        
        /// <remarks/>
        TJK,
        
        /// <remarks/>
        TKL,
        
        /// <remarks/>
        TKM,
        
        /// <remarks/>
        TLS,
        
        /// <remarks/>
        TON,
        
        /// <remarks/>
        TTO,
        
        /// <remarks/>
        TUN,
        
        /// <remarks/>
        TUR,
        
        /// <remarks/>
        TUV,
        
        /// <remarks/>
        TWN,
        
        /// <remarks/>
        TZA,
        
        /// <remarks/>
        UGA,
        
        /// <remarks/>
        UKR,
        
        /// <remarks/>
        UMI,
        
        /// <remarks/>
        RKS,
        
        /// <remarks/>
        URY,
        
        /// <remarks/>
        USA,
        
        /// <remarks/>
        UZB,
        
        /// <remarks/>
        VAT,
        
        /// <remarks/>
        VCT,
        
        /// <remarks/>
        VEN,
        
        /// <remarks/>
        VGB,
        
        /// <remarks/>
        VIR,
        
        /// <remarks/>
        VNM,
        
        /// <remarks/>
        VUT,
        
        /// <remarks/>
        WLF,
        
        /// <remarks/>
        WSM,
        
        /// <remarks/>
        YEM,
        
        /// <remarks/>
        ZAF,
        
        /// <remarks/>
        ZMB,
        
        /// <remarks/>
        ZWE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterInvoiceInputRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private string businessUnitCodeField;
        
        private InvoiceSType inoiceTypeField;
        
        private bool inoiceTypeFieldSpecified;
        
        private string invOrdNumField;
        
        private string invNumField;
        
        private System.DateTime sendDatetimeField;
        
        private bool isIssuerInVATField;
        
        private decimal taxFreeAmtField;
        
        private bool taxFreeAmtFieldSpecified;
        
        private decimal priceWithoutVATField;
        
        private bool priceWithoutVATFieldSpecified;
        
        private decimal vATAmountField;
        
        private bool vATAmountFieldSpecified;
        
        private decimal priceWithVATField;
        
        private bool priceWithVATFieldSpecified;
        
        private string deviceIDField;
        
        private string nrLiferimitField;
        
        private PaymentMethodTypeSType paymentMethodTypeSTypeField;
        
        private bool paymentMethodTypeSTypeFieldSpecified;
        
        private BuyerType buyerField;
        
        private InvoiceItemType[] invoiceItemsField;
        
        private string cardNumberField;
        
        private bool isReverseChargeField;
        
        private string iICRefField;
        
        private System.Nullable<System.DateTime> issueDateTimeRefField;
        
        private CorrectiveInvTypeSType typeRefField;
        
        private bool typeRefFieldSpecified;
        
        private bool isCorrectiveInvField;
        
        private string mobileRefIdField;
        
        private int subseqDelivTypeSTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
                this.RaisePropertyChanged("TCRCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BusinessUnitCode {
            get {
                return this.businessUnitCodeField;
            }
            set {
                this.businessUnitCodeField = value;
                this.RaisePropertyChanged("BusinessUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public InvoiceSType InoiceType {
            get {
                return this.inoiceTypeField;
            }
            set {
                this.inoiceTypeField = value;
                this.RaisePropertyChanged("InoiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InoiceTypeSpecified {
            get {
                return this.inoiceTypeFieldSpecified;
            }
            set {
                this.inoiceTypeFieldSpecified = value;
                this.RaisePropertyChanged("InoiceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string InvOrdNum {
            get {
                return this.invOrdNumField;
            }
            set {
                this.invOrdNumField = value;
                this.RaisePropertyChanged("InvOrdNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string InvNum {
            get {
                return this.invNumField;
            }
            set {
                this.invNumField = value;
                this.RaisePropertyChanged("InvNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime SendDatetime {
            get {
                return this.sendDatetimeField;
            }
            set {
                this.sendDatetimeField = value;
                this.RaisePropertyChanged("SendDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsIssuerInVAT {
            get {
                return this.isIssuerInVATField;
            }
            set {
                this.isIssuerInVATField = value;
                this.RaisePropertyChanged("IsIssuerInVAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal TaxFreeAmt {
            get {
                return this.taxFreeAmtField;
            }
            set {
                this.taxFreeAmtField = value;
                this.RaisePropertyChanged("TaxFreeAmt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxFreeAmtSpecified {
            get {
                return this.taxFreeAmtFieldSpecified;
            }
            set {
                this.taxFreeAmtFieldSpecified = value;
                this.RaisePropertyChanged("TaxFreeAmtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal PriceWithoutVAT {
            get {
                return this.priceWithoutVATField;
            }
            set {
                this.priceWithoutVATField = value;
                this.RaisePropertyChanged("PriceWithoutVAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceWithoutVATSpecified {
            get {
                return this.priceWithoutVATFieldSpecified;
            }
            set {
                this.priceWithoutVATFieldSpecified = value;
                this.RaisePropertyChanged("PriceWithoutVATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal VATAmount {
            get {
                return this.vATAmountField;
            }
            set {
                this.vATAmountField = value;
                this.RaisePropertyChanged("VATAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATAmountSpecified {
            get {
                return this.vATAmountFieldSpecified;
            }
            set {
                this.vATAmountFieldSpecified = value;
                this.RaisePropertyChanged("VATAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal PriceWithVAT {
            get {
                return this.priceWithVATField;
            }
            set {
                this.priceWithVATField = value;
                this.RaisePropertyChanged("PriceWithVAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceWithVATSpecified {
            get {
                return this.priceWithVATFieldSpecified;
            }
            set {
                this.priceWithVATFieldSpecified = value;
                this.RaisePropertyChanged("PriceWithVATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("DeviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NrLiferimit {
            get {
                return this.nrLiferimitField;
            }
            set {
                this.nrLiferimitField = value;
                this.RaisePropertyChanged("NrLiferimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public PaymentMethodTypeSType PaymentMethodTypeSType {
            get {
                return this.paymentMethodTypeSTypeField;
            }
            set {
                this.paymentMethodTypeSTypeField = value;
                this.RaisePropertyChanged("PaymentMethodTypeSType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentMethodTypeSTypeSpecified {
            get {
                return this.paymentMethodTypeSTypeFieldSpecified;
            }
            set {
                this.paymentMethodTypeSTypeFieldSpecified = value;
                this.RaisePropertyChanged("PaymentMethodTypeSTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public BuyerType Buyer {
            get {
                return this.buyerField;
            }
            set {
                this.buyerField = value;
                this.RaisePropertyChanged("Buyer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public InvoiceItemType[] InvoiceItems {
            get {
                return this.invoiceItemsField;
            }
            set {
                this.invoiceItemsField = value;
                this.RaisePropertyChanged("InvoiceItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsReverseCharge {
            get {
                return this.isReverseChargeField;
            }
            set {
                this.isReverseChargeField = value;
                this.RaisePropertyChanged("IsReverseCharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string IICRef {
            get {
                return this.iICRefField;
            }
            set {
                this.iICRefField = value;
                this.RaisePropertyChanged("IICRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<System.DateTime> IssueDateTimeRef {
            get {
                return this.issueDateTimeRefField;
            }
            set {
                this.issueDateTimeRefField = value;
                this.RaisePropertyChanged("IssueDateTimeRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public CorrectiveInvTypeSType TypeRef {
            get {
                return this.typeRefField;
            }
            set {
                this.typeRefField = value;
                this.RaisePropertyChanged("TypeRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeRefSpecified {
            get {
                return this.typeRefFieldSpecified;
            }
            set {
                this.typeRefFieldSpecified = value;
                this.RaisePropertyChanged("TypeRefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool IsCorrectiveInv {
            get {
                return this.isCorrectiveInvField;
            }
            set {
                this.isCorrectiveInvField = value;
                this.RaisePropertyChanged("IsCorrectiveInv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string MobileRefId {
            get {
                return this.mobileRefIdField;
            }
            set {
                this.mobileRefIdField = value;
                this.RaisePropertyChanged("MobileRefId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int SubseqDelivTypeSType {
            get {
                return this.subseqDelivTypeSTypeField;
            }
            set {
                this.subseqDelivTypeSTypeField = value;
                this.RaisePropertyChanged("SubseqDelivTypeSType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum InvoiceSType {
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        NONCASH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum PaymentMethodTypeSType {
        
        /// <remarks/>
        BANKNOTE,
        
        /// <remarks/>
        CARD,
        
        /// <remarks/>
        CHECK,
        
        /// <remarks/>
        SVOUCHER,
        
        /// <remarks/>
        COMPANY,
        
        /// <remarks/>
        ORDER,
        
        /// <remarks/>
        ACCOUNT,
        
        /// <remarks/>
        FACTORING,
        
        /// <remarks/>
        COMPENSATION,
        
        /// <remarks/>
        TRANSFER,
        
        /// <remarks/>
        WAIVER,
        
        /// <remarks/>
        KIND,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum CorrectiveInvTypeSType {
        
        /// <remarks/>
        CORRECTIVE,
        
        /// <remarks/>
        DEBIT,
        
        /// <remarks/>
        CREDIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterCashDepositInputRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal cashAmountField;
        
        private CashDepositOperationSType depositTypeField;
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private int subseqDelivTypeSTypeField;
        
        private System.DateTime sendDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal CashAmount {
            get {
                return this.cashAmountField;
            }
            set {
                this.cashAmountField = value;
                this.RaisePropertyChanged("CashAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CashDepositOperationSType DepositType {
            get {
                return this.depositTypeField;
            }
            set {
                this.depositTypeField = value;
                this.RaisePropertyChanged("DepositType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
                this.RaisePropertyChanged("TCRCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SubseqDelivTypeSType {
            get {
                return this.subseqDelivTypeSTypeField;
            }
            set {
                this.subseqDelivTypeSTypeField = value;
                this.RaisePropertyChanged("SubseqDelivTypeSType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime SendDateTime {
            get {
                return this.sendDateTimeField;
            }
            set {
                this.sendDateTimeField = value;
                this.RaisePropertyChanged("SendDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum CashDepositOperationSType {
        
        /// <remarks/>
        INITIAL,
        
        /// <remarks/>
        WITHDRAW,
        
        /// <remarks/>
        DEPOSIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseObjectField;
        
        private Status statusField;
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private string businessCodeField;
        
        private string tAGNRField;
        
        private string iDNField;
        
        private string levizjeIDNField;
        
        private string vitiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResponseObject {
            get {
                return this.responseObjectField;
            }
            set {
                this.responseObjectField = value;
                this.RaisePropertyChanged("ResponseObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
                this.RaisePropertyChanged("TCRCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BusinessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
                this.RaisePropertyChanged("BusinessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TAGNR {
            get {
                return this.tAGNRField;
            }
            set {
                this.tAGNRField = value;
                this.RaisePropertyChanged("TAGNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IDN {
            get {
                return this.iDNField;
            }
            set {
                this.iDNField = value;
                this.RaisePropertyChanged("IDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LevizjeIDN {
            get {
                return this.levizjeIDNField;
            }
            set {
                this.levizjeIDNField = value;
                this.RaisePropertyChanged("LevizjeIDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Viti {
            get {
                return this.vitiField;
            }
            set {
                this.vitiField = value;
                this.RaisePropertyChanged("Viti");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiscalisationServiceSoapChannel : ProjectTemplate1.ServiceReference1.FiscalisationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiscalisationServiceSoapClient : System.ServiceModel.ClientBase<ProjectTemplate1.ServiceReference1.FiscalisationServiceSoap>, ProjectTemplate1.ServiceReference1.FiscalisationServiceSoap {
        
        public FiscalisationServiceSoapClient() {
        }
        
        public FiscalisationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiscalisationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiscalisationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiscalisationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjectTemplate1.ServiceReference1.ResultLog RegisterTCR(string IDAgjenti, string businessUnitCode) {
            return base.Channel.RegisterTCR(IDAgjenti, businessUnitCode);
        }
        
        public System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterTCRAsync(string IDAgjenti, string businessUnitCode) {
            return base.Channel.RegisterTCRAsync(IDAgjenti, businessUnitCode);
        }
        
        public string GetTCRByIDAgjenti(string IDAgjenti) {
            return base.Channel.GetTCRByIDAgjenti(IDAgjenti);
        }
        
        public System.Threading.Tasks.Task<string> GetTCRByIDAgjentiAsync(string IDAgjenti) {
            return base.Channel.GetTCRByIDAgjentiAsync(IDAgjenti);
        }
        
        public ProjectTemplate1.ServiceReference1.ResultConfiguration GetConfigurationByIDAgjenti(string IDAgjenti) {
            return base.Channel.GetConfigurationByIDAgjenti(IDAgjenti);
        }
        
        public System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultConfiguration> GetConfigurationByIDAgjentiAsync(string IDAgjenti) {
            return base.Channel.GetConfigurationByIDAgjentiAsync(IDAgjenti);
        }
        
        public bool UpdateNumriFiskByIDAgjenti(string IDAgjenti, string TCRCode, int IDN, int LevizjeIDN) {
            return base.Channel.UpdateNumriFiskByIDAgjenti(IDAgjenti, TCRCode, IDN, LevizjeIDN);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateNumriFiskByIDAgjentiAsync(string IDAgjenti, string TCRCode, int IDN, int LevizjeIDN) {
            return base.Channel.UpdateNumriFiskByIDAgjentiAsync(IDAgjenti, TCRCode, IDN, LevizjeIDN);
        }
        
        public int CheckCorrectiveInvoice(string invId, string DeviceID, string TCRCode, string OperatorCode, string BusinessUnitCode, string NIPT) {
            return base.Channel.CheckCorrectiveInvoice(invId, DeviceID, TCRCode, OperatorCode, BusinessUnitCode, NIPT);
        }
        
        public System.Threading.Tasks.Task<int> CheckCorrectiveInvoiceAsync(string invId, string DeviceID, string TCRCode, string OperatorCode, string BusinessUnitCode, string NIPT) {
            return base.Channel.CheckCorrectiveInvoiceAsync(invId, DeviceID, TCRCode, OperatorCode, BusinessUnitCode, NIPT);
        }
        
        public string GetTCRRequestByMobleIdRef(string MobleIdRef) {
            return base.Channel.GetTCRRequestByMobleIdRef(MobleIdRef);
        }
        
        public System.Threading.Tasks.Task<string> GetTCRRequestByMobleIdRefAsync(string MobleIdRef) {
            return base.Channel.GetTCRRequestByMobleIdRefAsync(MobleIdRef);
        }
        
        public ProjectTemplate1.ServiceReference1.ResultLog RegisterCashDeposit(ProjectTemplate1.ServiceReference1.RegisterCashDepositInputRequest req) {
            return base.Channel.RegisterCashDeposit(req);
        }
        
        public System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterCashDepositAsync(ProjectTemplate1.ServiceReference1.RegisterCashDepositInputRequest req) {
            return base.Channel.RegisterCashDepositAsync(req);
        }
        
        public ProjectTemplate1.ServiceReference1.ResultLog RegisterInvoice(ProjectTemplate1.ServiceReference1.RegisterInvoiceInputRequest req) {
            return base.Channel.RegisterInvoice(req);
        }
        
        public System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterInvoiceAsync(ProjectTemplate1.ServiceReference1.RegisterInvoiceInputRequest req) {
            return base.Channel.RegisterInvoiceAsync(req);
        }
        
        public ProjectTemplate1.ServiceReference1.ResultLog RegisterWTN(ProjectTemplate1.ServiceReference1.RegisterWTNInputRequest req) {
            return base.Channel.RegisterWTN(req);
        }
        
        public System.Threading.Tasks.Task<ProjectTemplate1.ServiceReference1.ResultLog> RegisterWTNAsync(ProjectTemplate1.ServiceReference1.RegisterWTNInputRequest req) {
            return base.Channel.RegisterWTNAsync(req);
        }
    }
}
