//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EHW_M.Droid.FiskalizimiService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FiscalisationServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FiscalisationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterTCROperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTCRByIDAgjentiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConfigurationByIDAgjentiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNumriFiskByIDAgjentiOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckCorrectiveInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTCRRequestByMobleIdRefOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterCashDepositOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterWTNOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FiscalisationService() {
            this.Url = "http://84.22.42.59:5010/FiscalisationService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterTCRCompletedEventHandler RegisterTCRCompleted;
        
        /// <remarks/>
        public event GetTCRByIDAgjentiCompletedEventHandler GetTCRByIDAgjentiCompleted;
        
        /// <remarks/>
        public event GetConfigurationByIDAgjentiCompletedEventHandler GetConfigurationByIDAgjentiCompleted;
        
        /// <remarks/>
        public event UpdateNumriFiskByIDAgjentiCompletedEventHandler UpdateNumriFiskByIDAgjentiCompleted;
        
        /// <remarks/>
        public event CheckCorrectiveInvoiceCompletedEventHandler CheckCorrectiveInvoiceCompleted;
        
        /// <remarks/>
        public event GetTCRRequestByMobleIdRefCompletedEventHandler GetTCRRequestByMobleIdRefCompleted;
        
        /// <remarks/>
        public event RegisterCashDepositCompletedEventHandler RegisterCashDepositCompleted;
        
        /// <remarks/>
        public event RegisterInvoiceCompletedEventHandler RegisterInvoiceCompleted;
        
        /// <remarks/>
        public event RegisterWTNCompletedEventHandler RegisterWTNCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterTCR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultLog RegisterTCR(string IDAgjenti, string businessUnitCode) {
            object[] results = this.Invoke("RegisterTCR", new object[] {
                        IDAgjenti,
                        businessUnitCode});
            return ((ResultLog)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterTCRAsync(string IDAgjenti, string businessUnitCode) {
            this.RegisterTCRAsync(IDAgjenti, businessUnitCode, null);
        }
        
        /// <remarks/>
        public void RegisterTCRAsync(string IDAgjenti, string businessUnitCode, object userState) {
            if ((this.RegisterTCROperationCompleted == null)) {
                this.RegisterTCROperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterTCROperationCompleted);
            }
            this.InvokeAsync("RegisterTCR", new object[] {
                        IDAgjenti,
                        businessUnitCode}, this.RegisterTCROperationCompleted, userState);
        }
        
        private void OnRegisterTCROperationCompleted(object arg) {
            if ((this.RegisterTCRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterTCRCompleted(this, new RegisterTCRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTCRByIDAgjenti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTCRByIDAgjenti(string IDAgjenti) {
            object[] results = this.Invoke("GetTCRByIDAgjenti", new object[] {
                        IDAgjenti});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTCRByIDAgjentiAsync(string IDAgjenti) {
            this.GetTCRByIDAgjentiAsync(IDAgjenti, null);
        }
        
        /// <remarks/>
        public void GetTCRByIDAgjentiAsync(string IDAgjenti, object userState) {
            if ((this.GetTCRByIDAgjentiOperationCompleted == null)) {
                this.GetTCRByIDAgjentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTCRByIDAgjentiOperationCompleted);
            }
            this.InvokeAsync("GetTCRByIDAgjenti", new object[] {
                        IDAgjenti}, this.GetTCRByIDAgjentiOperationCompleted, userState);
        }
        
        private void OnGetTCRByIDAgjentiOperationCompleted(object arg) {
            if ((this.GetTCRByIDAgjentiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTCRByIDAgjentiCompleted(this, new GetTCRByIDAgjentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConfigurationByIDAgjenti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultConfiguration GetConfigurationByIDAgjenti(string IDAgjenti) {
            object[] results = this.Invoke("GetConfigurationByIDAgjenti", new object[] {
                        IDAgjenti});
            return ((ResultConfiguration)(results[0]));
        }
        
        /// <remarks/>
        public void GetConfigurationByIDAgjentiAsync(string IDAgjenti) {
            this.GetConfigurationByIDAgjentiAsync(IDAgjenti, null);
        }
        
        /// <remarks/>
        public void GetConfigurationByIDAgjentiAsync(string IDAgjenti, object userState) {
            if ((this.GetConfigurationByIDAgjentiOperationCompleted == null)) {
                this.GetConfigurationByIDAgjentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConfigurationByIDAgjentiOperationCompleted);
            }
            this.InvokeAsync("GetConfigurationByIDAgjenti", new object[] {
                        IDAgjenti}, this.GetConfigurationByIDAgjentiOperationCompleted, userState);
        }
        
        private void OnGetConfigurationByIDAgjentiOperationCompleted(object arg) {
            if ((this.GetConfigurationByIDAgjentiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConfigurationByIDAgjentiCompleted(this, new GetConfigurationByIDAgjentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateNumriFiskByIDAgjenti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateNumriFiskByIDAgjenti(string IDAgjenti, string TCRCode, int IDN, int LevizjeIDN) {
            object[] results = this.Invoke("UpdateNumriFiskByIDAgjenti", new object[] {
                        IDAgjenti,
                        TCRCode,
                        IDN,
                        LevizjeIDN});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateNumriFiskByIDAgjentiAsync(string IDAgjenti, string TCRCode, int IDN, int LevizjeIDN) {
            this.UpdateNumriFiskByIDAgjentiAsync(IDAgjenti, TCRCode, IDN, LevizjeIDN, null);
        }
        
        /// <remarks/>
        public void UpdateNumriFiskByIDAgjentiAsync(string IDAgjenti, string TCRCode, int IDN, int LevizjeIDN, object userState) {
            if ((this.UpdateNumriFiskByIDAgjentiOperationCompleted == null)) {
                this.UpdateNumriFiskByIDAgjentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNumriFiskByIDAgjentiOperationCompleted);
            }
            this.InvokeAsync("UpdateNumriFiskByIDAgjenti", new object[] {
                        IDAgjenti,
                        TCRCode,
                        IDN,
                        LevizjeIDN}, this.UpdateNumriFiskByIDAgjentiOperationCompleted, userState);
        }
        
        private void OnUpdateNumriFiskByIDAgjentiOperationCompleted(object arg) {
            if ((this.UpdateNumriFiskByIDAgjentiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNumriFiskByIDAgjentiCompleted(this, new UpdateNumriFiskByIDAgjentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckCorrectiveInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CheckCorrectiveInvoice(string invId, string DeviceID, string TCRCode, string OperatorCode, string BusinessUnitCode, string NIPT) {
            object[] results = this.Invoke("CheckCorrectiveInvoice", new object[] {
                        invId,
                        DeviceID,
                        TCRCode,
                        OperatorCode,
                        BusinessUnitCode,
                        NIPT});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CheckCorrectiveInvoiceAsync(string invId, string DeviceID, string TCRCode, string OperatorCode, string BusinessUnitCode, string NIPT) {
            this.CheckCorrectiveInvoiceAsync(invId, DeviceID, TCRCode, OperatorCode, BusinessUnitCode, NIPT, null);
        }
        
        /// <remarks/>
        public void CheckCorrectiveInvoiceAsync(string invId, string DeviceID, string TCRCode, string OperatorCode, string BusinessUnitCode, string NIPT, object userState) {
            if ((this.CheckCorrectiveInvoiceOperationCompleted == null)) {
                this.CheckCorrectiveInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCorrectiveInvoiceOperationCompleted);
            }
            this.InvokeAsync("CheckCorrectiveInvoice", new object[] {
                        invId,
                        DeviceID,
                        TCRCode,
                        OperatorCode,
                        BusinessUnitCode,
                        NIPT}, this.CheckCorrectiveInvoiceOperationCompleted, userState);
        }
        
        private void OnCheckCorrectiveInvoiceOperationCompleted(object arg) {
            if ((this.CheckCorrectiveInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCorrectiveInvoiceCompleted(this, new CheckCorrectiveInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTCRRequestByMobleIdRef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTCRRequestByMobleIdRef(string MobleIdRef) {
            object[] results = this.Invoke("GetTCRRequestByMobleIdRef", new object[] {
                        MobleIdRef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTCRRequestByMobleIdRefAsync(string MobleIdRef) {
            this.GetTCRRequestByMobleIdRefAsync(MobleIdRef, null);
        }
        
        /// <remarks/>
        public void GetTCRRequestByMobleIdRefAsync(string MobleIdRef, object userState) {
            if ((this.GetTCRRequestByMobleIdRefOperationCompleted == null)) {
                this.GetTCRRequestByMobleIdRefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTCRRequestByMobleIdRefOperationCompleted);
            }
            this.InvokeAsync("GetTCRRequestByMobleIdRef", new object[] {
                        MobleIdRef}, this.GetTCRRequestByMobleIdRefOperationCompleted, userState);
        }
        
        private void OnGetTCRRequestByMobleIdRefOperationCompleted(object arg) {
            if ((this.GetTCRRequestByMobleIdRefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTCRRequestByMobleIdRefCompleted(this, new GetTCRRequestByMobleIdRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterCashDeposit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultLog RegisterCashDeposit(RegisterCashDepositInputRequest req) {
            object[] results = this.Invoke("RegisterCashDeposit", new object[] {
                        req});
            return ((ResultLog)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterCashDepositAsync(RegisterCashDepositInputRequest req) {
            this.RegisterCashDepositAsync(req, null);
        }
        
        /// <remarks/>
        public void RegisterCashDepositAsync(RegisterCashDepositInputRequest req, object userState) {
            if ((this.RegisterCashDepositOperationCompleted == null)) {
                this.RegisterCashDepositOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterCashDepositOperationCompleted);
            }
            this.InvokeAsync("RegisterCashDeposit", new object[] {
                        req}, this.RegisterCashDepositOperationCompleted, userState);
        }
        
        private void OnRegisterCashDepositOperationCompleted(object arg) {
            if ((this.RegisterCashDepositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCashDepositCompleted(this, new RegisterCashDepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultLog RegisterInvoice(RegisterInvoiceInputRequest req) {
            object[] results = this.Invoke("RegisterInvoice", new object[] {
                        req});
            return ((ResultLog)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterInvoiceAsync(RegisterInvoiceInputRequest req) {
            this.RegisterInvoiceAsync(req, null);
        }
        
        /// <remarks/>
        public void RegisterInvoiceAsync(RegisterInvoiceInputRequest req, object userState) {
            if ((this.RegisterInvoiceOperationCompleted == null)) {
                this.RegisterInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterInvoiceOperationCompleted);
            }
            this.InvokeAsync("RegisterInvoice", new object[] {
                        req}, this.RegisterInvoiceOperationCompleted, userState);
        }
        
        private void OnRegisterInvoiceOperationCompleted(object arg) {
            if ((this.RegisterInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterInvoiceCompleted(this, new RegisterInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterWTN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultLog RegisterWTN(RegisterWTNInputRequest req) {
            object[] results = this.Invoke("RegisterWTN", new object[] {
                        req});
            return ((ResultLog)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterWTNAsync(RegisterWTNInputRequest req) {
            this.RegisterWTNAsync(req, null);
        }
        
        /// <remarks/>
        public void RegisterWTNAsync(RegisterWTNInputRequest req, object userState) {
            if ((this.RegisterWTNOperationCompleted == null)) {
                this.RegisterWTNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterWTNOperationCompleted);
            }
            this.InvokeAsync("RegisterWTN", new object[] {
                        req}, this.RegisterWTNOperationCompleted, userState);
        }
        
        private void OnRegisterWTNOperationCompleted(object arg) {
            if ((this.RegisterWTNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterWTNCompleted(this, new RegisterWTNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultLog {
        
        private System.DateTime createdField;
        
        private string requestField;
        
        private string responseField;
        
        private string responseObjectField;
        
        private Status statusField;
        
        private RequestType requestTypeField;
        
        private string stacktraceField;
        
        private string messageField;
        
        private string mobileIdRefField;
        
        private string operatorCodeField;
        
        private string qRCodeLinkField;
        
        private string tCRBusinessCodeField;
        
        private string nSLFField;
        
        private string nIVFField;
        
        private string responseUUIDField;
        
        private string eICField;
        
        private string responseUUIDSHField;
        
        private string nIVFSHField;
        
        private string nSLFSHField;
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseObject {
            get {
                return this.responseObjectField;
            }
            set {
                this.responseObjectField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public RequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Stacktrace {
            get {
                return this.stacktraceField;
            }
            set {
                this.stacktraceField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string MobileIdRef {
            get {
                return this.mobileIdRefField;
            }
            set {
                this.mobileIdRefField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string QRCodeLink {
            get {
                return this.qRCodeLinkField;
            }
            set {
                this.qRCodeLinkField = value;
            }
        }
        
        /// <remarks/>
        public string TCRBusinessCode {
            get {
                return this.tCRBusinessCodeField;
            }
            set {
                this.tCRBusinessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string NSLF {
            get {
                return this.nSLFField;
            }
            set {
                this.nSLFField = value;
            }
        }
        
        /// <remarks/>
        public string NIVF {
            get {
                return this.nIVFField;
            }
            set {
                this.nIVFField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseUUID {
            get {
                return this.responseUUIDField;
            }
            set {
                this.responseUUIDField = value;
            }
        }
        
        /// <remarks/>
        public string EIC {
            get {
                return this.eICField;
            }
            set {
                this.eICField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseUUIDSH {
            get {
                return this.responseUUIDSHField;
            }
            set {
                this.responseUUIDSHField = value;
            }
        }
        
        /// <remarks/>
        public string NIVFSH {
            get {
                return this.nIVFSHField;
            }
            set {
                this.nIVFSHField = value;
            }
        }
        
        /// <remarks/>
        public string NSLFSH {
            get {
                return this.nSLFSHField;
            }
            set {
                this.nSLFSHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Status {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        FaultCode,
        
        /// <remarks/>
        CertificateNotValid,
        
        /// <remarks/>
        InternalError,
        
        /// <remarks/>
        TCRAlreadyRegistered,
        
        /// <remarks/>
        InProcess,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum RequestType {
        
        /// <remarks/>
        Fault,
        
        /// <remarks/>
        Undefiend,
        
        /// <remarks/>
        RegisterTCR,
        
        /// <remarks/>
        RegisterCashDeposit,
        
        /// <remarks/>
        RegisterInvoice,
        
        /// <remarks/>
        RegisterWTN,
        
        /// <remarks/>
        RegisterEinvoice,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class WTNItemType {
        
        private string nField;
        
        private string cField;
        
        private string uField;
        
        private double qField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterWTNInputRequest {
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private string businessUnitCodeField;
        
        private string deviceIDField;
        
        private string invOrdNumField;
        
        private string invNumField;
        
        private System.DateTime sendDatetimeField;
        
        private decimal valueOfGoodsField;
        
        private bool startPointSTypeSpecified1Field;
        
        private WTNStartPointSType startPointSTypeField;
        
        private bool startPointSTypeFieldSpecified;
        
        private bool destinPointSTypeSpecified1Field;
        
        private WTNDestinPointSType destinPointSTypeField;
        
        private bool destinPointSTypeFieldSpecified;
        
        private WTNItemType[] transferItemsField;
        
        private string mobileRefIdField;
        
        private int subseqDelivTypeSTypeField;
        
        private string fromDeviceIdField;
        
        private string toDeviceIdField;
        
        /// <remarks/>
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessUnitCode {
            get {
                return this.businessUnitCodeField;
            }
            set {
                this.businessUnitCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
            }
        }
        
        /// <remarks/>
        public string InvOrdNum {
            get {
                return this.invOrdNumField;
            }
            set {
                this.invOrdNumField = value;
            }
        }
        
        /// <remarks/>
        public string InvNum {
            get {
                return this.invNumField;
            }
            set {
                this.invNumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendDatetime {
            get {
                return this.sendDatetimeField;
            }
            set {
                this.sendDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValueOfGoods {
            get {
                return this.valueOfGoodsField;
            }
            set {
                this.valueOfGoodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartPointSTypeSpecified")]
        public bool StartPointSTypeSpecified1 {
            get {
                return this.startPointSTypeSpecified1Field;
            }
            set {
                this.startPointSTypeSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public WTNStartPointSType StartPointSType {
            get {
                return this.startPointSTypeField;
            }
            set {
                this.startPointSTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartPointSTypeSpecified {
            get {
                return this.startPointSTypeFieldSpecified;
            }
            set {
                this.startPointSTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinPointSTypeSpecified")]
        public bool DestinPointSTypeSpecified1 {
            get {
                return this.destinPointSTypeSpecified1Field;
            }
            set {
                this.destinPointSTypeSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public WTNDestinPointSType DestinPointSType {
            get {
                return this.destinPointSTypeField;
            }
            set {
                this.destinPointSTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DestinPointSTypeSpecified {
            get {
                return this.destinPointSTypeFieldSpecified;
            }
            set {
                this.destinPointSTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public WTNItemType[] TransferItems {
            get {
                return this.transferItemsField;
            }
            set {
                this.transferItemsField = value;
            }
        }
        
        /// <remarks/>
        public string MobileRefId {
            get {
                return this.mobileRefIdField;
            }
            set {
                this.mobileRefIdField = value;
            }
        }
        
        /// <remarks/>
        public int SubseqDelivTypeSType {
            get {
                return this.subseqDelivTypeSTypeField;
            }
            set {
                this.subseqDelivTypeSTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FromDeviceId {
            get {
                return this.fromDeviceIdField;
            }
            set {
                this.fromDeviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string ToDeviceId {
            get {
                return this.toDeviceIdField;
            }
            set {
                this.toDeviceIdField = value;
            }
        }

    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum WTNStartPointSType {
        
        /// <remarks/>
        WAREHOUSE,
        
        /// <remarks/>
        EXHIBITION,
        
        /// <remarks/>
        STORE,
        
        /// <remarks/>
        SALE,
        
        /// <remarks/>
        ANOTHER,
        
        /// <remarks/>
        CUSTOMS,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum WTNDestinPointSType {
        
        /// <remarks/>
        WAREHOUSE,
        
        /// <remarks/>
        EXHIBITION,
        
        /// <remarks/>
        STORE,
        
        /// <remarks/>
        SALE,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class VoucherType {
        
        private string numField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class VoucherSoldDataType {
        
        private System.DateTime dField;
        
        private decimal nField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class VouchersSoldType {
        
        private VoucherSoldDataType vdField;
        
        private VoucherType[] vnField;
        
        /// <remarks/>
        public VoucherSoldDataType VD {
            get {
                return this.vdField;
            }
            set {
                this.vdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("V", IsNullable=false)]
        public VoucherType[] VN {
            get {
                return this.vnField;
            }
            set {
                this.vnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class InvoiceItemType {
        
        private VouchersSoldType vsField;
        
        private string nField;
        
        private string cField;
        
        private string uField;
        
        private double qField;
        
        private decimal uPBField;
        
        private decimal uPAField;
        
        private decimal rField;
        
        private bool rFieldSpecified;
        
        private bool rrField;
        
        private bool rrFieldSpecified;
        
        private decimal pbField;
        
        private decimal vrField;
        
        private bool vrFieldSpecified;
        
        private decimal vaField;
        
        private bool vaFieldSpecified;
        
        private bool inField;
        
        private bool inFieldSpecified;
        
        private decimal paField;
        
        private ExemptFromVATSType exField;
        
        private bool exFieldSpecified;
        
        /// <remarks/>
        public VouchersSoldType VS {
            get {
                return this.vsField;
            }
            set {
                this.vsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal UPB {
            get {
                return this.uPBField;
            }
            set {
                this.uPBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal UPA {
            get {
                return this.uPAField;
            }
            set {
                this.uPAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSpecified {
            get {
                return this.rFieldSpecified;
            }
            set {
                this.rFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool RR {
            get {
                return this.rrField;
            }
            set {
                this.rrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RRSpecified {
            get {
                return this.rrFieldSpecified;
            }
            set {
                this.rrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PB {
            get {
                return this.pbField;
            }
            set {
                this.pbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal VR {
            get {
                return this.vrField;
            }
            set {
                this.vrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VRSpecified {
            get {
                return this.vrFieldSpecified;
            }
            set {
                this.vrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal VA {
            get {
                return this.vaField;
            }
            set {
                this.vaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VASpecified {
            get {
                return this.vaFieldSpecified;
            }
            set {
                this.vaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IN {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INSpecified {
            get {
                return this.inFieldSpecified;
            }
            set {
                this.inFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PA {
            get {
                return this.paField;
            }
            set {
                this.paField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ExemptFromVATSType EX {
            get {
                return this.exField;
            }
            set {
                this.exField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EXSpecified {
            get {
                return this.exFieldSpecified;
            }
            set {
                this.exFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum ExemptFromVATSType {
        
        /// <remarks/>
        TYPE_1,
        
        /// <remarks/>
        TYPE_2,
        
        /// <remarks/>
        TAX_FREE,
        
        /// <remarks/>
        MARGIN_SCHEME,
        
        /// <remarks/>
        EXPORT_OF_GOODS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public partial class BuyerType {
        
        private IDTypeSType iDTypeField;
        
        private bool iDTypeFieldSpecified;
        
        private string iDNumField;
        
        private string nameField;
        
        private string addressField;
        
        private string townField;
        
        private CountryCodeSType countryField;
        
        private bool countryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public IDTypeSType IDType {
            get {
                return this.iDTypeField;
            }
            set {
                this.iDTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDTypeSpecified {
            get {
                return this.iDTypeFieldSpecified;
            }
            set {
                this.iDTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IDNum {
            get {
                return this.iDNumField;
            }
            set {
                this.iDNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CountryCodeSType Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountrySpecified {
            get {
                return this.countryFieldSpecified;
            }
            set {
                this.countryFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum IDTypeSType {
        
        /// <remarks/>
        NUIS,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        PASS,
        
        /// <remarks/>
        VAT,
        
        /// <remarks/>
        TAX,
        
        /// <remarks/>
        SOC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum CountryCodeSType {
        
        /// <remarks/>
        ABW,
        
        /// <remarks/>
        AFG,
        
        /// <remarks/>
        AGO,
        
        /// <remarks/>
        AIA,
        
        /// <remarks/>
        ALA,
        
        /// <remarks/>
        ALB,
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        ARE,
        
        /// <remarks/>
        ARG,
        
        /// <remarks/>
        ARM,
        
        /// <remarks/>
        ASM,
        
        /// <remarks/>
        ATA,
        
        /// <remarks/>
        ATF,
        
        /// <remarks/>
        ATG,
        
        /// <remarks/>
        AUS,
        
        /// <remarks/>
        AUT,
        
        /// <remarks/>
        AZE,
        
        /// <remarks/>
        BDI,
        
        /// <remarks/>
        BEL,
        
        /// <remarks/>
        BEN,
        
        /// <remarks/>
        BES,
        
        /// <remarks/>
        BFA,
        
        /// <remarks/>
        BGD,
        
        /// <remarks/>
        BGR,
        
        /// <remarks/>
        BHR,
        
        /// <remarks/>
        BHS,
        
        /// <remarks/>
        BIH,
        
        /// <remarks/>
        BLM,
        
        /// <remarks/>
        BLR,
        
        /// <remarks/>
        BLZ,
        
        /// <remarks/>
        BMU,
        
        /// <remarks/>
        BOL,
        
        /// <remarks/>
        BRA,
        
        /// <remarks/>
        BRB,
        
        /// <remarks/>
        BRN,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BVT,
        
        /// <remarks/>
        BWA,
        
        /// <remarks/>
        CAF,
        
        /// <remarks/>
        CAN,
        
        /// <remarks/>
        CCK,
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        CHL,
        
        /// <remarks/>
        CHN,
        
        /// <remarks/>
        CIV,
        
        /// <remarks/>
        CMR,
        
        /// <remarks/>
        COD,
        
        /// <remarks/>
        COG,
        
        /// <remarks/>
        COK,
        
        /// <remarks/>
        COL,
        
        /// <remarks/>
        COM,
        
        /// <remarks/>
        CPV,
        
        /// <remarks/>
        CRI,
        
        /// <remarks/>
        CUB,
        
        /// <remarks/>
        CUW,
        
        /// <remarks/>
        CXR,
        
        /// <remarks/>
        CYM,
        
        /// <remarks/>
        CYP,
        
        /// <remarks/>
        CZE,
        
        /// <remarks/>
        DEU,
        
        /// <remarks/>
        DJI,
        
        /// <remarks/>
        DMA,
        
        /// <remarks/>
        DNK,
        
        /// <remarks/>
        DOM,
        
        /// <remarks/>
        DZA,
        
        /// <remarks/>
        ECU,
        
        /// <remarks/>
        EGY,
        
        /// <remarks/>
        ERI,
        
        /// <remarks/>
        ESH,
        
        /// <remarks/>
        ESP,
        
        /// <remarks/>
        EST,
        
        /// <remarks/>
        ETH,
        
        /// <remarks/>
        FIN,
        
        /// <remarks/>
        FJI,
        
        /// <remarks/>
        FLK,
        
        /// <remarks/>
        FRA,
        
        /// <remarks/>
        FRO,
        
        /// <remarks/>
        FSM,
        
        /// <remarks/>
        GAB,
        
        /// <remarks/>
        GBR,
        
        /// <remarks/>
        GEO,
        
        /// <remarks/>
        GGY,
        
        /// <remarks/>
        GHA,
        
        /// <remarks/>
        GIB,
        
        /// <remarks/>
        GIN,
        
        /// <remarks/>
        GLP,
        
        /// <remarks/>
        GMB,
        
        /// <remarks/>
        GNB,
        
        /// <remarks/>
        GNQ,
        
        /// <remarks/>
        GRC,
        
        /// <remarks/>
        GRD,
        
        /// <remarks/>
        GRL,
        
        /// <remarks/>
        GTM,
        
        /// <remarks/>
        GUF,
        
        /// <remarks/>
        GUM,
        
        /// <remarks/>
        GUY,
        
        /// <remarks/>
        HKG,
        
        /// <remarks/>
        HMD,
        
        /// <remarks/>
        HND,
        
        /// <remarks/>
        HRV,
        
        /// <remarks/>
        HTI,
        
        /// <remarks/>
        HUN,
        
        /// <remarks/>
        IDN,
        
        /// <remarks/>
        IMN,
        
        /// <remarks/>
        IND,
        
        /// <remarks/>
        IOT,
        
        /// <remarks/>
        IRL,
        
        /// <remarks/>
        IRN,
        
        /// <remarks/>
        IRQ,
        
        /// <remarks/>
        ISL,
        
        /// <remarks/>
        ISR,
        
        /// <remarks/>
        ITA,
        
        /// <remarks/>
        JAM,
        
        /// <remarks/>
        JEY,
        
        /// <remarks/>
        JOR,
        
        /// <remarks/>
        JPN,
        
        /// <remarks/>
        KAZ,
        
        /// <remarks/>
        KEN,
        
        /// <remarks/>
        KGZ,
        
        /// <remarks/>
        KHM,
        
        /// <remarks/>
        KIR,
        
        /// <remarks/>
        KNA,
        
        /// <remarks/>
        KOR,
        
        /// <remarks/>
        KWT,
        
        /// <remarks/>
        LAO,
        
        /// <remarks/>
        LBN,
        
        /// <remarks/>
        LBR,
        
        /// <remarks/>
        LBY,
        
        /// <remarks/>
        LCA,
        
        /// <remarks/>
        LIE,
        
        /// <remarks/>
        LKA,
        
        /// <remarks/>
        LSO,
        
        /// <remarks/>
        LTU,
        
        /// <remarks/>
        LUX,
        
        /// <remarks/>
        LVA,
        
        /// <remarks/>
        MAC,
        
        /// <remarks/>
        MAF,
        
        /// <remarks/>
        MAR,
        
        /// <remarks/>
        MCO,
        
        /// <remarks/>
        MDA,
        
        /// <remarks/>
        MDG,
        
        /// <remarks/>
        MDV,
        
        /// <remarks/>
        MEX,
        
        /// <remarks/>
        MHL,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MLI,
        
        /// <remarks/>
        MLT,
        
        /// <remarks/>
        MMR,
        
        /// <remarks/>
        MNE,
        
        /// <remarks/>
        MNG,
        
        /// <remarks/>
        MNP,
        
        /// <remarks/>
        MOZ,
        
        /// <remarks/>
        MRT,
        
        /// <remarks/>
        MSR,
        
        /// <remarks/>
        MTQ,
        
        /// <remarks/>
        MUS,
        
        /// <remarks/>
        MWI,
        
        /// <remarks/>
        MYS,
        
        /// <remarks/>
        MYT,
        
        /// <remarks/>
        NAM,
        
        /// <remarks/>
        NCL,
        
        /// <remarks/>
        NER,
        
        /// <remarks/>
        NFK,
        
        /// <remarks/>
        NGA,
        
        /// <remarks/>
        NIC,
        
        /// <remarks/>
        NIU,
        
        /// <remarks/>
        NLD,
        
        /// <remarks/>
        NOR,
        
        /// <remarks/>
        NPL,
        
        /// <remarks/>
        NRU,
        
        /// <remarks/>
        NZL,
        
        /// <remarks/>
        OMN,
        
        /// <remarks/>
        PAK,
        
        /// <remarks/>
        PAN,
        
        /// <remarks/>
        PCN,
        
        /// <remarks/>
        PER,
        
        /// <remarks/>
        PHL,
        
        /// <remarks/>
        PLW,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        POL,
        
        /// <remarks/>
        PRI,
        
        /// <remarks/>
        PRK,
        
        /// <remarks/>
        PRT,
        
        /// <remarks/>
        PRY,
        
        /// <remarks/>
        PSE,
        
        /// <remarks/>
        PYF,
        
        /// <remarks/>
        QAT,
        
        /// <remarks/>
        REU,
        
        /// <remarks/>
        ROU,
        
        /// <remarks/>
        RUS,
        
        /// <remarks/>
        RWA,
        
        /// <remarks/>
        SAU,
        
        /// <remarks/>
        SDN,
        
        /// <remarks/>
        SEN,
        
        /// <remarks/>
        SGP,
        
        /// <remarks/>
        SGS,
        
        /// <remarks/>
        SHN,
        
        /// <remarks/>
        SJM,
        
        /// <remarks/>
        SLB,
        
        /// <remarks/>
        SLE,
        
        /// <remarks/>
        SLV,
        
        /// <remarks/>
        SMR,
        
        /// <remarks/>
        SOM,
        
        /// <remarks/>
        SPM,
        
        /// <remarks/>
        SRB,
        
        /// <remarks/>
        SSD,
        
        /// <remarks/>
        STP,
        
        /// <remarks/>
        SUR,
        
        /// <remarks/>
        SVK,
        
        /// <remarks/>
        SVN,
        
        /// <remarks/>
        SWE,
        
        /// <remarks/>
        SWZ,
        
        /// <remarks/>
        SXM,
        
        /// <remarks/>
        SYC,
        
        /// <remarks/>
        SYR,
        
        /// <remarks/>
        TCA,
        
        /// <remarks/>
        TCD,
        
        /// <remarks/>
        TGO,
        
        /// <remarks/>
        THA,
        
        /// <remarks/>
        TJK,
        
        /// <remarks/>
        TKL,
        
        /// <remarks/>
        TKM,
        
        /// <remarks/>
        TLS,
        
        /// <remarks/>
        TON,
        
        /// <remarks/>
        TTO,
        
        /// <remarks/>
        TUN,
        
        /// <remarks/>
        TUR,
        
        /// <remarks/>
        TUV,
        
        /// <remarks/>
        TWN,
        
        /// <remarks/>
        TZA,
        
        /// <remarks/>
        UGA,
        
        /// <remarks/>
        UKR,
        
        /// <remarks/>
        UMI,
        
        /// <remarks/>
        RKS,
        
        /// <remarks/>
        URY,
        
        /// <remarks/>
        USA,
        
        /// <remarks/>
        UZB,
        
        /// <remarks/>
        VAT,
        
        /// <remarks/>
        VCT,
        
        /// <remarks/>
        VEN,
        
        /// <remarks/>
        VGB,
        
        /// <remarks/>
        VIR,
        
        /// <remarks/>
        VNM,
        
        /// <remarks/>
        VUT,
        
        /// <remarks/>
        WLF,
        
        /// <remarks/>
        WSM,
        
        /// <remarks/>
        YEM,
        
        /// <remarks/>
        ZAF,
        
        /// <remarks/>
        ZMB,
        
        /// <remarks/>
        ZWE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterInvoiceInputRequest {
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private string businessUnitCodeField;
        
        private InvoiceSType inoiceTypeField;
        
        private bool inoiceTypeFieldSpecified;
        
        private string invOrdNumField;
        
        private string invNumField;
        
        private System.DateTime sendDatetimeField;
        
        private bool isIssuerInVATField;
        
        private decimal taxFreeAmtField;
        
        private bool taxFreeAmtFieldSpecified;
        
        private decimal priceWithoutVATField;
        
        private bool priceWithoutVATFieldSpecified;
        
        private decimal vATAmountField;
        
        private bool vATAmountFieldSpecified;
        
        private decimal priceWithVATField;
        
        private bool priceWithVATFieldSpecified;
        
        private string deviceIDField;
        
        private string nrLiferimitField;
        
        private PaymentMethodTypeSType paymentMethodTypeSTypeField;
        
        private bool paymentMethodTypeSTypeFieldSpecified;
        
        private BuyerType buyerField;
        
        private InvoiceItemType[] invoiceItemsField;
        
        private string cardNumberField;
        
        private bool isReverseChargeField;
        
        private string iICRefField;
        
        private System.Nullable<System.DateTime> issueDateTimeRefField;
        
        private CorrectiveInvTypeSType typeRefField;
        
        private bool typeRefFieldSpecified;
        
        private bool isCorrectiveInvField;
        
        private string mobileRefIdField;
        
        private int subseqDelivTypeSTypeField;
        
        /// <remarks/>
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessUnitCode {
            get {
                return this.businessUnitCodeField;
            }
            set {
                this.businessUnitCodeField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceSType InoiceType {
            get {
                return this.inoiceTypeField;
            }
            set {
                this.inoiceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InoiceTypeSpecified {
            get {
                return this.inoiceTypeFieldSpecified;
            }
            set {
                this.inoiceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string InvOrdNum {
            get {
                return this.invOrdNumField;
            }
            set {
                this.invOrdNumField = value;
            }
        }
        
        /// <remarks/>
        public string InvNum {
            get {
                return this.invNumField;
            }
            set {
                this.invNumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendDatetime {
            get {
                return this.sendDatetimeField;
            }
            set {
                this.sendDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsIssuerInVAT {
            get {
                return this.isIssuerInVATField;
            }
            set {
                this.isIssuerInVATField = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxFreeAmt {
            get {
                return this.taxFreeAmtField;
            }
            set {
                this.taxFreeAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxFreeAmtSpecified {
            get {
                return this.taxFreeAmtFieldSpecified;
            }
            set {
                this.taxFreeAmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PriceWithoutVAT {
            get {
                return this.priceWithoutVATField;
            }
            set {
                this.priceWithoutVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceWithoutVATSpecified {
            get {
                return this.priceWithoutVATFieldSpecified;
            }
            set {
                this.priceWithoutVATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal VATAmount {
            get {
                return this.vATAmountField;
            }
            set {
                this.vATAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATAmountSpecified {
            get {
                return this.vATAmountFieldSpecified;
            }
            set {
                this.vATAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PriceWithVAT {
            get {
                return this.priceWithVATField;
            }
            set {
                this.priceWithVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceWithVATSpecified {
            get {
                return this.priceWithVATFieldSpecified;
            }
            set {
                this.priceWithVATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
            }
        }
        
        /// <remarks/>
        public string NrLiferimit {
            get {
                return this.nrLiferimitField;
            }
            set {
                this.nrLiferimitField = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethodTypeSType PaymentMethodTypeSType {
            get {
                return this.paymentMethodTypeSTypeField;
            }
            set {
                this.paymentMethodTypeSTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentMethodTypeSTypeSpecified {
            get {
                return this.paymentMethodTypeSTypeFieldSpecified;
            }
            set {
                this.paymentMethodTypeSTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public BuyerType Buyer {
            get {
                return this.buyerField;
            }
            set {
                this.buyerField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceItemType[] InvoiceItems {
            get {
                return this.invoiceItemsField;
            }
            set {
                this.invoiceItemsField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool IsReverseCharge {
            get {
                return this.isReverseChargeField;
            }
            set {
                this.isReverseChargeField = value;
            }
        }
        
        /// <remarks/>
        public string IICRef {
            get {
                return this.iICRefField;
            }
            set {
                this.iICRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> IssueDateTimeRef {
            get {
                return this.issueDateTimeRefField;
            }
            set {
                this.issueDateTimeRefField = value;
            }
        }
        
        /// <remarks/>
        public CorrectiveInvTypeSType TypeRef {
            get {
                return this.typeRefField;
            }
            set {
                this.typeRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeRefSpecified {
            get {
                return this.typeRefFieldSpecified;
            }
            set {
                this.typeRefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsCorrectiveInv {
            get {
                return this.isCorrectiveInvField;
            }
            set {
                this.isCorrectiveInvField = value;
            }
        }
        
        /// <remarks/>
        public string MobileRefId {
            get {
                return this.mobileRefIdField;
            }
            set {
                this.mobileRefIdField = value;
            }
        }
        
        /// <remarks/>
        public int SubseqDelivTypeSType {
            get {
                return this.subseqDelivTypeSTypeField;
            }
            set {
                this.subseqDelivTypeSTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum InvoiceSType {
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        NONCASH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum PaymentMethodTypeSType {
        
        /// <remarks/>
        BANKNOTE,
        
        /// <remarks/>
        CARD,
        
        /// <remarks/>
        CHECK,
        
        /// <remarks/>
        SVOUCHER,
        
        /// <remarks/>
        COMPANY,
        
        /// <remarks/>
        ORDER,
        
        /// <remarks/>
        ACCOUNT,
        
        /// <remarks/>
        FACTORING,
        
        /// <remarks/>
        COMPENSATION,
        
        /// <remarks/>
        TRANSFER,
        
        /// <remarks/>
        WAIVER,
        
        /// <remarks/>
        KIND,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum CorrectiveInvTypeSType {
        
        /// <remarks/>
        CORRECTIVE,
        
        /// <remarks/>
        DEBIT,
        
        /// <remarks/>
        CREDIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterCashDepositInputRequest {
        
        private decimal cashAmountField;
        
        private CashDepositOperationSType depositTypeField;
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private int subseqDelivTypeSTypeField;
        
        private System.DateTime sendDateTimeField;
        
        /// <remarks/>
        public decimal CashAmount {
            get {
                return this.cashAmountField;
            }
            set {
                this.cashAmountField = value;
            }
        }
        
        /// <remarks/>
        public CashDepositOperationSType DepositType {
            get {
                return this.depositTypeField;
            }
            set {
                this.depositTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SubseqDelivTypeSType {
            get {
                return this.subseqDelivTypeSTypeField;
            }
            set {
                this.subseqDelivTypeSTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendDateTime {
            get {
                return this.sendDateTimeField;
            }
            set {
                this.sendDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema")]
    public enum CashDepositOperationSType {
        
        /// <remarks/>
        INITIAL,
        
        /// <remarks/>
        WITHDRAW,
        
        /// <remarks/>
        DEPOSIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultConfiguration {
        
        private string responseObjectField;
        
        private Status statusField;
        
        private string tCRCodeField;
        
        private string operatorCodeField;
        
        private string businessCodeField;
        
        private string tAGNRField;
        
        private string iDNField;
        
        private string levizjeIDNField;
        
        private string vitiField;
        
        /// <remarks/>
        public string ResponseObject {
            get {
                return this.responseObjectField;
            }
            set {
                this.responseObjectField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TCRCode {
            get {
                return this.tCRCodeField;
            }
            set {
                this.tCRCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TAGNR {
            get {
                return this.tAGNRField;
            }
            set {
                this.tAGNRField = value;
            }
        }
        
        /// <remarks/>
        public string IDN {
            get {
                return this.iDNField;
            }
            set {
                this.iDNField = value;
            }
        }
        
        /// <remarks/>
        public string LevizjeIDN {
            get {
                return this.levizjeIDNField;
            }
            set {
                this.levizjeIDNField = value;
            }
        }
        
        /// <remarks/>
        public string Viti {
            get {
                return this.vitiField;
            }
            set {
                this.vitiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegisterTCRCompletedEventHandler(object sender, RegisterTCRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterTCRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterTCRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultLog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultLog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTCRByIDAgjentiCompletedEventHandler(object sender, GetTCRByIDAgjentiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTCRByIDAgjentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTCRByIDAgjentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetConfigurationByIDAgjentiCompletedEventHandler(object sender, GetConfigurationByIDAgjentiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConfigurationByIDAgjentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConfigurationByIDAgjentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultConfiguration Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultConfiguration)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateNumriFiskByIDAgjentiCompletedEventHandler(object sender, UpdateNumriFiskByIDAgjentiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateNumriFiskByIDAgjentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateNumriFiskByIDAgjentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckCorrectiveInvoiceCompletedEventHandler(object sender, CheckCorrectiveInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCorrectiveInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCorrectiveInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTCRRequestByMobleIdRefCompletedEventHandler(object sender, GetTCRRequestByMobleIdRefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTCRRequestByMobleIdRefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTCRRequestByMobleIdRefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegisterCashDepositCompletedEventHandler(object sender, RegisterCashDepositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCashDepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCashDepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultLog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultLog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegisterInvoiceCompletedEventHandler(object sender, RegisterInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultLog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultLog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegisterWTNCompletedEventHandler(object sender, RegisterWTNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterWTNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterWTNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultLog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultLog)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591